### ISSUE TITLE
code:VariableName literals return variable name when it's undefined

### ISSUE THREAD

**Issue by tpluscode** [zazuko/rdf-loader-code#20]
In barnard59, if a step argument is declared as variable:

```turtle
[] a :Step ; 
  code:arguments 
    [
      code:name "graph" ;
      code:value "sourceGraph"^^:VariableName
    ] ;
.
```

and the variable `sourceGraph` is not set then the literal's value [will be returned](https://github.com/zazuko/rdf-loader-code/blob/master/arguments.js#L36-L38)

I think that a literal with datatype other than `xsd:string` should be returned as `undefined` if that's what the loader returns.

**Comment by bergos** [comment]
fixed in https://github.com/zazuko/barnard59-core/pull/66
